import React from 'react';
import { Navbar, Footer } from '../../components';
import styles from './page.module.scss';
import Link from 'next/link';
import WaveformAnim from '@/components/Waveform/WaveformAnim';
import Image from 'next/image';
import VideoInterface from '@/public/images/easy-connecting.webp';
  
import AudioTap from '@/public/icons/audio-tap.svg';
import HumanFirst from '@/public/icons/soul.svg';
import ZeroPersistence from '@/public/icons/ram-only.svg';
import HumanSignature from '@/public/icons/human-first.svg';
import { SessionTimeline } from '@/components/SessionTimeline/SessionTimeline';

import { JobsSection } from '@/components/JTBDSection/JobsSecton';
import ZenNotesFAQ from '@/components/ZenNotesFAQ';

import PatientNoteMockup from '@/components/PatientNotesMockup/PatientNoteMockup';
import BillingTab from '@/public/images/superbill_final.png';
import CTASection from '@/components/CTASection/CTASection';
import FAQ from '@/components/FAQ/FAQ';

export const metadata = {
  title: 'ZenNotes',
  description: 'Your private space for notes and journaling',
};

// ─── Data ─────────────────────────────────────────────────────────────────────

const FEATURES = [
  {
    icon: AudioTap,
    title: 'High-Fidelity Audio Tap',
    body: 'We\'re built into the call, not watching from outside, which means studio-quality audio. We capture the soul of the session, not just the computer audio.',
  },
  {
    icon: HumanFirst,
    title: 'AI is the muscle. You are the soul.',
    body: 'The system simultaneously handles documentation, ICD-10 coding, and generating plain-language patient summaries.',
  },
  {
    icon: ZeroPersistence,
    title: 'Zero-Persistence Privacy.',
    body: 'Audio is processed in real-time and not permanently stored, adhering to the highest trust and HIPAA standards.',
  },
  {
    icon: HumanSignature,
    title: 'Human Final Signature.',
    body: 'Every note remains a draft until you authenticate it. You provide the soul.',
  },
];

const PRIVACY_BULLETS = [
  'No Meeting Bots.',
  'No Blood Audio.',
  'No Cloud Storage.',
  'Pure Actuation.',
];

const BILLING_BULLETS = [
  {
    // "i": GetPaid,
    "h": 'Auto-Coding',
    "b": 'Our Ambient AI maps your session to the exact CPT and ICD-10 codes, ensuring you are paid accurately for your time.'
  },

  {
    // "i": Sync,
    "h": 'One-Click Delivery',
    "b": 'Generate, sign, and sync to your EHR or email directly to your client.'
  },
  {
    // "i": Audit,
    "h": 'Audit Protection',
    "b": 'Every bill is backed by the "Clinical Pulse" of the session, providing a verifiable trail of medical necessity.',
  }
];

const zenNotesFaqs = [
  [
    'How is Zenspace different from other AI note-takers?',
    'Most AI tools are "wrappers" that rely on third-party bots like Zoom or Teams bots and store your data on their servers. ZenSpace is a Sovereign Infrastructure built on a custom, low-latency WebRTC stack. We own the data pipe, which means no third-party bots ever join your calls, and no data is ever "leaked" to external meeting platforms.',
  ],
  [
    'Does Zenspace store audio recordings of my sessions?',
    'No. We use Zero-Persistence RAM-Only processing. Clinical audio is streamed directly into our secure environment, processed in volatile memory (RAM), and then essentially "evaporated" once the session documentation is generated. We do not store audio files, and we do not use your sessions to train our AI models.',
  ],
  [
    'Is Zenspace HIPAA compliant?',
    'Yes. ZenSpace is built to exceed 2026 HIPAA and global data integrity standards. Because we own our infrastructure and utilize zero-persistence processing, we provide a level of security that legacy "cloud-storage" AI tools cannot match. We are a secure conduit for your clinical data, not a warehouse.',
  ],
  [
    'Who owns the clinical notes generated by ZenNotes?',
    'You do. You have full ownership and control over all documentation. ZenNotes acts as your autonomous clinical assistant, drafting SOAP notes that are 95% complete by the time your session ends, but you remain the final authority and "Human-in-the-loop" for all clinical records.',
  ],
  [
    'How do you handle data during mobile-to-web handoffs?',
    'We use our proprietary EZLink Deep-Routing Layer. This ensures that clinical intent and data persistence are maintained securely across devices without exposing sensitive information to insecure mobile clipboards or third-party linking services.',
  ],
  ];

// ────────────────────────────────────────────────────────────────────────

export default function ZenNotesPage() {
  return (
    <div className={styles.page}>
      <Navbar />

      <main className={styles.content}>
        <section className={styles.hero}>
          <div className={styles.heroText}>
            <div className={styles.heroEyebrow}>
              {/* <WaveformAnim /> */}
              <span>Ambient Clinical Intelligence</span>
            </div>
            <h1>
              <span className={styles.line}>Your session ends.</span>
              <span className={styles.line}>Your notes are</span>
              <span className={styles.line}>already <em>done.</em></span>
            </h1>
            <p>
              Capture every nuance. Our Ambient AI transcribes the soul of the session,
              not just the computer audio.
            </p>
            <Link
              className="btn btn--primary  fade show"
              href="https://docs.google.com/forms/d/e/1FAIpQLSfwzPnrq_3K4zCOhyUdhwroBsw-haYHsY6Xn4wgRUXCCB8Urw/viewform?usp=header"
              target="_blank"
              rel="noopener noreferrer"
              >
              Get Early Access
            </Link>
          </div>
          <div className={styles.postSessionTimeline}>
            <SessionTimeline autoPlay loop loopDelay={2200} showReplay={false} />
          </div>
        </section>

        {/* ── Trust Bar ── */}
      <section className={`${styles.trustBar} full-bleed--edge`}>
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1rem'}}>
          <WaveformAnim />
        </div>
        <h2 className={styles.trustHeading}>Built for the most sensitive<br />conversations on earth.</h2>
        <p className={styles.trustSub}>Enter Ambient Clinical Intelligence (ACI).</p>

        <div className={styles.featuresGrid}>
          {FEATURES.map((f) => (
            <div className={styles.featureCard} key={f.title}>
              <Image
                src={f.icon}
                alt={`${f.title} icon`}
                height={32}
                width={32}
                style={{
                  marginBottom: '1rem',
                }}
                className={styles.featureIcon}
              />
              <h3>{f.title}</h3>
              <p>{f.body}</p>
            </div>
          ))}
        </div>
        </section>
        <JobsSection />
        {/* ── We Own The Pipes Section ── */}
      <section className={styles.pipesSection}>
        <div style={{ maxWidth: '600px', margin: '0 auto 4rem', textAlign: 'center' }}>
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1rem'}}>
            <WaveformAnim />
          </div>
          <h2 style={{marginTop: '2rem'}}>Studio-quality calls</h2>
          <p className={styles.pipesSub}>
            ZenNotes is built into the call — not a passive recorder watching from outside.
            That&apos;s why we catch what others miss, and why nothing ever joins your session uninvited.
          </p>
          </div>
        <div className={styles.pipesInner}>
          <div className={styles.pipesImage}>
            {/* Replace with <Image src="/assets/zennotes-video-call.png" alt="Video calling interface" fill /> */}
            <Image
              src={VideoInterface}
              alt="Video calling interface"
            />
          </div>

          <div className={styles.pipesText}>
            <ul className={styles.pipesList}>
              <li>
                <div className={styles.pipesItemHeader}>
                  {/* <span className={styles.pipesItemDot} /> */}
                  <strong>Direct Stream Extraction</strong>
                </div>
                <p>We process <b>audio and video natively delivering a seamless HD experience</b>.
                  No Bots, no third-party API lag, no security middlemen.</p>
              </li>
              <li>
                <div className={styles.pipesItemHeader}>
                  {/* <span className={styles.pipesItemDot} /> */}
                  <strong>Instantaneous Processing</strong>
                </div>
                <p>
                  Audio is analyzed and evaporates as soon as the session ends.
                  We <b>deliver the intelligence</b>, not the liability.
                </p>
              </li>
              <li>
                <div className={styles.pipesItemHeader}>
                  {/* <span className={styles.pipesItemDot} /> */}
                  <strong>Agentic Context Synthesis</strong>
                </div>
                <p>Unlike legacy scribes, we don&apos;t just transcribe; we <b>synthesize the Affect and Thematic Memory </b> directly into the note.</p>
              </li>
            </ul>
            </div>
          </div>
        </section>

        {/* ── Privacy Section ── */}
      <section className={`${styles.privacySection} full-bleed--edge`}>
        <div className={styles.privacyInner}>
          <div className={` ${styles.privacyPhone}`}>
            <div className={styles.phoneWrapper}>
              <WaveformAnim />
            </div>
          </div>

          <div className={styles.privacyText}>
            <h2>Zero-Persistence. Total Privacy.</h2>
            <p className={styles.privacySub}>
              Unlike wrappers that store data in the cloud, ZenNotes is <b>RAM-only processing</b>.
              Your audio is processed in real-time and then discarded, ensuring that your
              sensitive conversations never touch the cloud.
            </p>
            <ul className={styles.privacyBullets}>
              {PRIVACY_BULLETS.map((b) => (
                <li key={b}>{b}</li>
              ))}
            </ul>
          </div>
        </div>
      </section>
        {/* ── Public Notes Section ── */}
      <section className={styles.publicSection}>
        <div className={styles.publicText}>
          <h2>Private and public notes. Finally!</h2>
          <p className={styles.publicSub}>
            Your SOAP note stays yours — <b>  encrypted, HIPAA-compliant, audit-ready</b>.
            Your patient gets context — names, team, actionable.
            <b> Same session. Two truths</b>. Both honored.
          </p>
        </div>

        <PatientNoteMockup />
      </section>
       {/* ── Billing Section ── */}
      <section className={`${styles.billingSection} full-bleed--edge`}>
        <div className={styles.billingInner}>
          <Image 
            src={BillingTab}
            alt="Superbill preview"
            height={600}
            width={0}
            className={styles.imgHero}
            
          />
          <div className={styles.billingContent}>
            <div className={styles.headerGroup}>
              <h2>The End of Billing Fatigue</h2>
              <p className={styles.subheadline}>
                From Session to Superbill in 90 Seconds.
              </p>
            </div>
            
            <div className={styles.billingList}>
              {BILLING_BULLETS.map((b, idx) => (
                <div key={idx} className={styles.bulletItem}>
                  <span className={styles.bulletTitle}>{b.h}. </span>
                  <span className={styles.bulletBody}>{b.b}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
        </section>  
        <FAQ 
          title="Privacy & Trust" 
          items={zenNotesFaqs} 
          brand="notes" 
        />
        <CTASection />
    </main>
    <Footer />
    </div>
  );
}
